export const BabyHealthAndHygiene = {
  meta: {
    id: "BabyHealthAndHygiene",
    name: "Baby Health & Hygiene",
    color: "#F2C94C",
    description: "",
  },
  actionCards: [{
    title: (babyName) => `Feed ${babyName}`,
    ref: 'baby',
    subtitle: null,
    helpLink: "https://www.babycenter.com/0_age-by-age-guide-to-feeding-your-baby_1400680.bc",
    helpText: null,
    minAge: 15552000,
    maxAge: null,
  }, {
    title: (babyName) => `Burp ${babyName}`,
    ref: 'baby',
    subtitle: null,
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: 15552000,
  }, {
    title: (babyName) => `Give ${babyName} a bath`,
    ref: 'baby',
    subtitle: null,
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: null,
  }, {
    title: "Make a baby-proofing improvement",
    subtitle: null,
    helpLink: "https://www.parents.com/baby/safety/babyproofing/babyproofing-basics/",
    helpText: null,
    minAge: null,
    maxAge: null,
  }, {
    title: (babyName) => `Change ${babyName}’s diaper`,
    ref: 'baby',
    subtitle: "If it's not dirty, be the one to do it next",
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: 94610000,
  }, {
    title: "Buy baby supplies",
    subtitle: "(find out what's needed)",
    helpLink: null,
    helpText: "Is there enough of the following?: diapers, baby wipes, hand wipes, baby shampoo, baby soap, baby lotion, diaper rash cream, baby dishes, baby utensils, baby cups",
    minAge: null,
    maxAge: null,
  },
  ]
}
