export const HouseholdChores = {
  meta: {
    id: "HouseholdChores",
    name: "Household Chores",
    color: "#27AE60",
    description: "",
  },
  actionCards: [{
    title: "Pick any shared room in the house and clean it thoroughly",
    subtitle: null,
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: null,
  }, {
    title: "Collect and wash dirty dishes",
    subtitle: null,
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: null,
  }, {
    title: "Do a load of laundry other than your own",
    subtitle: null,
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: null,
  }, {
    title: "Make dinner for the family",
    subtitle: null,
    helpLink: "https://www.babycenter.com/0_age-by-age-guide-to-feeding-your-baby_1400680.bc",
    helpText: null,
    minAge: null,
    maxAge: null,
  }, {
    title: "Prepare lunches for the family",
    subtitle: null,
    helpLink: "https://www.babycenter.com/0_age-by-age-guide-to-feeding-your-baby_1400680.bc",
    helpText: null,
    minAge: null,
    maxAge: null,
  }, {
    title: "Take out the dirty diaper bin",
    subtitle: "and any other trash",
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: null,
  }, {
    title: "Change and wash the sheets for all beds",
    subtitle: null,
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: null,
  }, {
    title: "Pick up toys at the end of the day",
    subtitle: null,
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: null,
  }, {
    title: (babyName) => `Clean floors for ${babyName}’s crawling`,
    who: 'baby',
    subtitle: "(floors need to be extra clean)",
    helpLink: null,
    helpText: null,
    minAge: 15552000,
    maxAge: null,
  }, {
    title: "Buy a week’s worth of groceries",
    subtitle: "(come up with the shopping list)",
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: null,
  },
  ]
}
