export const SchedulesAndCommunication = {
  meta: {
    id: "SchedulesAndCommunication",
    name: "Schedules & Communication",
    color: "#BB6BD9",
    description: "",
  },
  actionCards: [{
    title: (babyName) => `Schedule an appointment for ${babyName}`,
    who: 'baby',
    subtitle: "(find out when the next pediatrician or dentist visit should be)",
    helpLink: "https://www.thebump.com/a/new-baby-doctor-visit-checklist",
    helpText: "If your pediatrician / dentist office has an online portal, log in and check for appointment scheduling reminders.",
    minAge: null,
    maxAge: null,
    nanny: false,
  }, {
    title: "Coordinate with the nanny or other caregiver",
    subtitle: null,
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: null,
    nanny: true,
  }, {
    title: (babyName) => `Schedule a playdate for ${babyName}`,
    who: 'baby',
    subtitle: "and plan to be there yourself",
    helpLink: null,
    helpText: null,
    minAge: 15552000,
    maxAge: null,
    nanny: false,
  }, {
    title: "Schedule an outside activity or lesson",
    subtitle: "(do some research to find one)",
    helpLink: null,
    helpText: "Look at your local libraries' schedule of events for story time, music, sign language, etc.",
    minAge: 7776000,
    maxAge: null,
    nanny: false,
  }, {
    title: (babyName) => `Schedule yourself to pick-up/drop-off ${babyName} at the nanny's`,
    who: 'baby',
    subtitle: "(or other caregiver's)",
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: null,
    nanny: true,
  }, {
    title: "Send a thank you note for a baby gift",
    subtitle: "(a text message will do!)",
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: null,
    nanny: false,
  }, {
    title: "Buy a gift for an upcoming occasion",
    subtitle: "Any birthdays or family visits coming up?",
    helpLink: null,
    helpText: null,
    minAge: null,
    maxAge: null,
    nanny: false,
  },
  ]
};
